homework_project/customauth/urls.py
from django.urls import re_path

from django.contrib.auth.models import User

### see => https://simpleisbetterthancomplex.com/tutorial/2016/06/27/how-to-use-djangos-built-in-login-system.html
from django.contrib.auth import views as auth_views


###
### uninstalled django 2.1 
### and than installed 2.0.7, so auth_views works!
###


from . import views as custom_auth_views

app_name = 'custom_auth'

urlpatterns = [

    re_path(r'^signup/$', custom_auth_views.signup, name='signup'),
    re_path(r'^login/$', auth_views.login, name='login'), 
    re_path(r'^logout/$', auth_views.logout, {'next_page': 'learning:courses_list'} , name='logout'),

]

homework_project/homework_project/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [

    path('learning/', include('learning.urls')),
    path('auth/', include('customauth.urls')),
    path('admin/', admin.site.urls),

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

homework_project/learning/urls.py
from django.urls import path

from . import views

app_name = 'learning'

urlpatterns = [
    
    path('', views.AboutView.as_view(), name='about'),

    path('courses', views.CourseList.as_view(), name='courses_list'),
    
    path('courses/<int:pk>', views.LessonDetail.as_view(), name='lesson_detail'),
    
    path('courses/<slug:slug>', views.CourseDetail.as_view(), name='course_detail'),
    

]

homework_project/customauth/models.py
from django.db import models

# Create your models here.

homework_project/learning/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=512)
    description = models.TextField()
    name_for_slug = str(name)
    slug = models.SlugField(default = name_for_slug)
    
    def __str__(self):
        return str(self.name)
    
    
class Lesson(models.Model):
    name = models.CharField(max_length=512)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank = True)

    def __str__(self):
        return str(self.name)



    

homework_project/customauth/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


### see => https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('learning:courses_list')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

homework_project/learning/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse

from django.views.generic import TemplateView, ListView, DetailView


from .models import Course, Lesson

class AboutView(TemplateView):
    template_name = "learning/about.html"


class CourseList(ListView):
    model = Course
    course_id = Course.pk
    ##contest_object_name = 'my_courses'  ???


class CourseDetail(DetailView):
    model = Course
    
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        self.course = get_object_or_404(Course, slug = self.kwargs['slug'])    
        
        context['lessons_list'] = Lesson.objects.filter(course=self.course)
        
        return context
    
    queryset = Course.objects.all()
    


class LessonDetail(DetailView):
    model = Lesson

    

homework_project/learning/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">



    {% block title %}

    {% endblock %}



    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



    <!-- Custom styles for this template -->
    <link href="{% static 'styles.css' %}" rel="stylesheet">



  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Learning site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning:courses_list'%}">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Конспект</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>

            {% if user.is_authenticated %}
                 <li class="nav-item"> <a class="nav-link disabled" href="#"> User: {{ user.get_username }} </a></li>

                 <li class="nav-item"><a class="nav-link" href="{% url 'custom_auth:logout'%}?next={% url 'learning:courses_list' %}">Logout</a></li>  


               {% else %}
                 <li class="nav-item"><a class="nav-link" href="{% url 'custom_auth:login'%}?next={% url 'learning:courses_list' %}">Login</a></li> 
                 <li class="nav-item"><a class="nav-link" href="{% url 'custom_auth:signup'%}?next={% url 'learning:courses_list' %}">Register</a></li>   
               {% endif %} 

          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">

	{% block content %}



	{% endblock %}


    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   
  </body>
</html>

homework_project/learning/templates/learning/about.html
{% extends 'base.html' %}


{% block title %}

	<title> About </title>

{% endblock %}



{% block content %}

      <h1> Hello from about page </h1>


      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>


{% endblock %}

homework_project/learning/templates/learning/course_detail.html
{% extends 'base.html' %}


{% block title %}

	<title> {{ course.name }} </title>

{% endblock %}



{% block content %}
	
	<h3>  {{ course.name }}  </h3>

	<div>

	<p> {{ course.description }}  <p/>
	</div>

	<ul>

		{% for lesson in lessons_list %}
	
			<li>
			<a href="{% url 'learning:lesson_detail' lesson.pk %}"> {{ lesson.name }} </a>
			</li>
			
		{% endfor %}
	
	</ul>
	

	<div>
		<a href="{% url 'learning:courses_list' %}"> Back to courses list </a>
	</div>

{% endblock %}

homework_project/learning/templates/learning/course_list.html
{% extends 'base.html' %}


{% block title %}

	<title> Courses </title>

{% endblock %}



{% block content %}
	

	<ul>

		{% for course in object_list %}

		
			<li>
		           <h3>
			      <a href="{% url 'learning:course_detail' course.slug %}"> {{ course.name }} </a>
			   </h3>
			</li>
			

		{% endfor %}
		
		
	
	</ul>



{% endblock %}

homework_project/learning/templates/learning/lesson_detail.html
{% extends 'base.html' %}


{% block title %}

	<title> {{ lesson.name }} </title>

{% endblock %}



{% block content %}
	
	<h3>  {{ lesson.name }}  </h3>

	<div>

	<p> {{ lesson.description }}  <p/>
	</div>
	

	<div>
		<a href="{% url 'learning:course_detail' lesson.course.slug %}"> Back to course description </a>
	</div>

{% endblock %}